// Copyright 2016-2018 LG Electronics, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

#ifndef UI_EVENTS_KEYCODES_WEBOS_HARDWARE_CODES_H_
#define UI_EVENTS_KEYCODES_WEBOS_HARDWARE_CODES_H_

// hardware keycode : IM keycode
// As a IM keycode, 0x04C9 (1225) is max value
#define KEY_MAX 1225

#define HARDWARE_LGE_LEFT      0x0069
#define HARDWARE_LGE_RIGHT     0x006A
#define HARDWARE_LGE_UP        0x0067
#define HARDWARE_LGE_DOWN      0x006C
#define HARDWARE_LGE_TAB       0x000F

/* Media Buttons */
#define HARDWARE_LGE_MEDIAPLAY      0x00CF
#define HARDWARE_LGE_MEDIASTOP      0x0080
#define HARDWARE_LGE_MEDIAPREVIOUS  0x032D
#define HARDWARE_LGE_MEDIANEXT      0x032E
#define HARDWARE_LGE_MEDIARECORD    0x00A7
#define HARDWARE_LGE_AUDIOREWIND    0x00A8
#define HARDWARE_LGE_AUDIOFORWARD   0x00D0
#define HARDWARE_LGE_SUBTITLE       0x031F

/* VOLUME BUTTON */
#define HARDWARE_LGE_VOLUMEDOWN    0x0072
#define HARDWARE_LGE_VOLUMEMUTE    0x0071
#define HARDWARE_LGE_VOLUMEUP      0x0073

/* MISC BUTTONS */
#define HARDWARE_LGE_SUPER_L    0x0305
#define HARDWARE_LGE_OPTION     0x03FE
#define HARDWARE_LGE_VIDEO      0x03FF

/* WEBOS BUTTONS */
#define HARDWARE_LGE_POWERONOFF     0x0074
#define HARDWARE_LGE_EXIT           0x00AE
#define HARDWARE_LGE_INFO           0x0166
#define HARDWARE_LGE_BACK           0x019C
#define HARDWARE_LGE_SETTINGS       0x008B
#define HARDWARE_LGE_RECENT         0x03F0
#define HARDWARE_LGE_RED            0x018E
#define HARDWARE_LGE_GREEN          0x018F
#define HARDWARE_LGE_YELLOW         0x0190
#define HARDWARE_LGE_BLUE           0x0191
#define HARDWARE_LGE_TWIN           0x0401
#define HARDWARE_LGE_MAGNIFIERZOOM  0x0402
#define HARDWARE_LGE_LIVEZOOM       0x0403
#define HARDWARE_LGE_STB_MENU       0x0404
#define HARDWARE_LGE_STB_POWER      0x408
#define HARDWARE_LGE_CHANNELUP      0x0192
#define HARDWARE_LGE_CHANNELDOWN    0x0193
#define HARDWARE_LGE_CHANNELDASH    0x0303
#define HARDWARE_LGE_CHANNELBACK    0x0304
#define HARDWARE_LGE_FAVORITE       0x016C
#define HARDWARE_LGE_SETCHANNEL     0x03DF
#define HARDWARE_LGE_TIMERPOWERON   0x409
#define HARDWARE_LGE_3DMODE         0x0335
#define HARDWARE_LGE_SCREENREMOTE   0x03E2
#define HARDWARE_LGE_QMENU          0x0319
#define HARDWARE_LGE_VOICE          0x01AC
#define HARDWARE_LGE_INPUTSOURCE    0x00F1
#define HARDWARE_LGE_INPUTTV        0x0179
#define HARDWARE_LGE_ASPECTRATIO    0x031D
#define HARDWARE_LGE_LIVETVMENU     0x0309
#define HARDWARE_LGE_TVGUIDE        0x016a
#define HARDWARE_LGE_AUDIODESCRIPTION   0x033D
#define HARDWARE_LGE_MHP            0x0328
#define HARDWARE_LGE_TELETEXT       0x030B
#define HARDWARE_LGE_TEXTOPTION     0x030C
#define HARDWARE_LGE_TEXTMODE       0x030D
#define HARDWARE_LGE_TEXTMIX        0x030E
#define HARDWARE_LGE_TELETEXTSUBPAGE    0x030F
#define HARDWARE_LGE_TELETEXTREVEAL 0x0310
#define HARDWARE_LGE_TELETEXTFREEZE 0x0311
#define HARDWARE_LGE_TELETEXTPOSITION   0x0315
#define HARDWARE_LGE_TELETEXTSIZE   0x0316
#define HARDWARE_LGE_TELETEXTINTIME 0x038D

#define HARDWARE_LGE_SIMPLINK   0x030A
#define HARDWARE_LGE_MULTIPIP   0x03C8
#define HARDWARE_LGE_INPUTTVRADIO   0x0318
#define HARDWARE_LGE_PROGRAMLIST    0x0313
#define HARDWARE_LGE_RECORDLIST     0x0090
#define HARDWARE_LGE_STOREMODE      0x0301

/* LOCAL KEYS (FRONT PANEL BUTTONS) */
#define HARDWARE_LGE_LOCALUP    0x0398
#define HARDWARE_LGE_LOCALDOWN  0x0399
#define HARDWARE_LGE_LOCALLEFT  0x039B
#define HARDWARE_LGE_LOCALRIGHT 0x039A
#define HARDWARE_LGE_LOCALENTER 0x03E8
#define HARDWARE_LGE_LOCALLONGPRESS 0x03E9
#define HARDWARE_LGE_LOCALPOWER 0x039C

/* JAPAN ONLY */
#define HARDWARE_LGE_BS             0x0340
#define HARDWARE_LGE_CS1            0x034D
#define HARDWARE_LGE_CS2            0x035A
#define HARDWARE_LGE_TER            0x0367
#define HARDWARE_LGE_3DIGITINPUT    0x0374
#define HARDWARE_LGE_BMLDATA        0x0375
#define HARDWARE_LGE_JAPANDISPLAY   0x0376
#define HARDWARE_LGE_BS_1           0x0341
#define HARDWARE_LGE_BS_2           0x0342
#define HARDWARE_LGE_BS_3           0x0343
#define HARDWARE_LGE_BS_4           0x0344
#define HARDWARE_LGE_BS_5           0x0345
#define HARDWARE_LGE_BS_6           0x0346
#define HARDWARE_LGE_BS_7           0x0347
#define HARDWARE_LGE_BS_8           0x0348
#define HARDWARE_LGE_BS_9           0x0349
#define HARDWARE_LGE_BS_10          0x034A
#define HARDWARE_LGE_BS_11          0x034B
#define HARDWARE_LGE_BS_12          0x034C
#define HARDWARE_LGE_CS1_1          0x034E
#define HARDWARE_LGE_CS1_2          0x034F
#define HARDWARE_LGE_CS1_3          0x0350
#define HARDWARE_LGE_CS1_4          0x0351
#define HARDWARE_LGE_CS1_5          0x0352
#define HARDWARE_LGE_CS1_6          0x0353
#define HARDWARE_LGE_CS1_7          0x0354
#define HARDWARE_LGE_CS1_8          0x0355
#define HARDWARE_LGE_CS1_9          0x0356
#define HARDWARE_LGE_CS1_10         0x0357
#define HARDWARE_LGE_CS1_11         0x0358
#define HARDWARE_LGE_CS1_12         0x0359
#define HARDWARE_LGE_CS2_1          0x035B
#define HARDWARE_LGE_CS2_2          0x035C
#define HARDWARE_LGE_CS2_3          0x035D
#define HARDWARE_LGE_CS2_4          0x035E
#define HARDWARE_LGE_CS2_5          0x035F
#define HARDWARE_LGE_CS2_6          0x0360
#define HARDWARE_LGE_CS2_7          0x0361
#define HARDWARE_LGE_CS2_8          0x0362
#define HARDWARE_LGE_CS2_9          0x0363
#define HARDWARE_LGE_CS2_10         0x0364
#define HARDWARE_LGE_CS2_11         0x0365
#define HARDWARE_LGE_CS2_12         0x0366
#define HARDWARE_LGE_TER_1          0x0368
#define HARDWARE_LGE_TER_2          0x0369
#define HARDWARE_LGE_TER_3          0x036A
#define HARDWARE_LGE_TER_4          0x036B
#define HARDWARE_LGE_TER_5          0x036C
#define HARDWARE_LGE_TER_6          0x036D
#define HARDWARE_LGE_TER_7          0x036E
#define HARDWARE_LGE_TER_8          0x036F
#define HARDWARE_LGE_TER_9          0x0370
#define HARDWARE_LGE_TER_10         0x0371
#define HARDWARE_LGE_TER_11         0x0372
#define HARDWARE_LGE_TER_12         0x0373

/* IT IS NOT A PHYSICAL BUTTON, BUT ACTS LIKE A KEY */
#define HARDWARE_LGE_CURSORSHOW     0x04AE
#define HARDWARE_LGE_CURSORHIDE     0x04AF

/* FOR COMMERCIAL MODEL */
#define HARDWARE_LGE_TVLINK         0x03EA
#define HARDWARE_LGE_HOTELMODE      0x3D9
#define HARDWARE_LGE_HOTELMODEREADY 0x3DA

// webOS3.5 hot key
#define HARDWARE_LGE_IVI            0x40F

/* FACTORY KEYS, IT IS USED TO CHECK THE SPECIFIC FUNCTIONALITY IN THE FACTORY,
   OR ADJUST THE SYSTEM INTERNAL SETTINGS BY THE DEVELOPERS. */
#define HARDWARE_LGE_FACTORYPOWERONLY   0x0387   /* P-ONLY */
#define HARDWARE_LGE_FACTORYINSTART     0x0383   /* IN START */
#define HARDWARE_LGE_FACTORYINSTOP      0x0382   /* IN STOP */
#define HARDWARE_LGE_FACTORYADJUST      0x0388   /* ADJ */
#define HARDWARE_LGE_FACTORYTV          0x03B3   /* TV */
#define HARDWARE_LGE_FACTORYVIDEO1      0x03B6   /* AV1 */
#define HARDWARE_LGE_FACTORYVIDEO2      0x03B7   /* AV2 */
#define HARDWARE_LGE_FACTORYCOMPONENT1  0x03B9   /* COMP1 */
#define HARDWARE_LGE_FACTORYCOMPONENT2  0x03BA   /* COMP2 */
#define HARDWARE_LGE_FACTORYHDMI1       0x03BF   /* HDMI1 */
#define HARDWARE_LGE_FACTORYHDMI2       0x03C0   /* HDMI2 */
#define HARDWARE_LGE_FACTORYHDMI3       0x03C1   /* HDMI3 */
#define HARDWARE_LGE_FACTORYHDMI4       0x03C2   /* HDMI4 */
#define HARDWARE_LGE_FACTORYRGBPC       0x03BC   /* RGB */
#define HARDWARE_LGE_FACTORYEYEQ        0x0381   /* EYE */
#define HARDWARE_LGE_FACTORYPICTUREMODE 0x0320   /* PSM */
#define HARDWARE_LGE_FACTORYSOUNDMODE   0x0321   /* SSM */
#define HARDWARE_LGE_FACTORYPICTURECHECK    0x0384   /* P-CHECK */
#define HARDWARE_LGE_FACTORYSOUNDCHECK      0x0386   /* S-CHECK */
#define HARDWARE_LGE_FACTORYMULTISOUNDSETTING   0x031E   /* MPX */
#define HARDWARE_LGE_FACTORYTILT                0x0393   /* TILT */
#define HARDWARE_LGE_FACTORYPIP                 0x031A   /* PIP */
#define HARDWARE_LGE_FACTORYHDMICHECK           0x0385   /* HDMI HOT */
#define HARDWARE_LGE_FACTORYUSBCHECK            0x0391   /* USB HOT */
#define HARDWARE_LGE_FACTORYUSB2CHECK           0x0392   /* USB HOT */
#define HARDWARE_LGE_FACTORYPOWEROFF            0x03AF   /* 'DISCRETE IR POWER OFF' */
#define HARDWARE_LGE_FACTORYPOWERON             0x03AE   /* 'DISCRETE IR POWER ON' */
#define HARDWARE_LGE_FACTORYSUBSTRATE           0x03C7   /* 'CHANGE MODE TO CIRCUIT BOARD PRODUCT' */
#define HARDWARE_LGE_FACTORYVOLUME30            0x03C3   /* 'SET VOLUME TO 30' */
#define HARDWARE_LGE_FACTORYVOLUME50            0x03C4   /* 'SET VOLUME TO 50' */
#define HARDWARE_LGE_FACTORYVOLUME80            0x03C5   /* 'SET VOLUME TO 80' */
#define HARDWARE_LGE_FACTORYVOLUME100           0x03C6   /* 'SET VOLUME TO 100' */
#define HARDWARE_LGE_FACTORYWHITEBALANCE        0x03C9   /* 'ADJUST WHITE BALANCE' */
#define HARDWARE_LGE_FACTORY3DPATTERN           0x03E3   /* '3D PATTERN' */
#define HARDWARE_LGE_FACTORYSELFDIAGNOSIS       0x03CB   /* 'SELF DIAGNOSIS' */
#define HARDWARE_LGE_FACTORYPATTERNCHECK        0x0406   /* 'PATTERN CHECK ON P-ONLY MODE' */
/* ANOTHER KEY CODES FOR LOCAL KEYS (POWER ONLY FULL-WHITE MODE) */
#define HARDWARE_LGE_FACTORYLOCALUP             0x0398
#define HARDWARE_LGE_FACTORYLOCALDOWN           0x0399
#define HARDWARE_LGE_FACTORYLOCALLEFT           0x039B
#define HARDWARE_LGE_FACTORYLOCALRIGHT          0x039A
#define HARDWARE_LGE_FACTORYLOCALENTER          0x0397

#endif  // UI_EVENTS_KEYCODES_WEBOS_HARDWARE_CODES_H_
