/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "453804577f3fe8652dbc7da7bf0dfca7b2c04de4"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
